# Generated by Django 6.0.3 on 2026-03-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='modeified_on',
            new_name='modified_on',
        ),
    ]
